---
apiVersion: v1
kind: Service
metadata:
   name: postgresql-service
   namespace: kafka-ca1
spec:
   type: ExternalName
   externalName: host.docker.internal
   ports:
   - name: port
     port: 5432
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: postgresql-service
# subsets:
#   - addresses:
#       - ip: 192.168.77.1
#     ports:
#       - port: 3306