apiVersion: v1
kind: Service
metadata:
  labels:
    name: consumerservice
  name: consumerservice
spec:
  ports:
    # The port that this service should serve on.
    - port: 8098
      targetPort: 8098
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: consumer-ms
  type: NodePort